config/routes.rb
Rails.application.routes.draw do
  # get 'relationships/followings'
  # get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search"=>"searches#search"
  get "search_book" => "books#search_book"
  get 'chat/:id', to: 'chats#show', as: 'chat'
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end  
  
  resources :chats, only: [:create]

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update]

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search' => 'users#search'
    # 上記追加
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # has_many :user_rooms, dependent: :destroy
  # has_many :chats, dependent: :destroy
  # 下記が解答のコードで上記が参考サイトのコード
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  has_one_attached :profile_image
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship",foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :view_counts, dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  # フォローした時の処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content+'%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%'+content)
    else
      User.where('name LIKE ?', '%'+content+'%')
    end
  end
  
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end  

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]
  before_action :ensure_guest_user, only: [:edit]

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end

  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book =  @books.created_today
    @yesterday_book = @books.created_yesterday
    @two_day_ago_book = @books.created_two_day_ago
    @three_day_ago_book = @books.created_three_day_ago
    @four_day_ago_book = @books.created_four_day_ago
    @five_day_ago_book = @books.created_five_day_ago
    @six_day_ago_book = @books.created_six_day_ago
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end


  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
      # (current_user.id)じゃなくていい
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_book_comment.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td class="comments_count_<%= book.id %>">コメント数:<%= book.book_comments.count %></td>
        
        <td id="star-rate<%= book.id %>"></td>
          <script>
            $('#star-rate<%= book.id %>').raty({
              size      : 36,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              half      : false,
              readOnly: true,
              score: '<%= book.star %>',
            });
          </script>
          
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_book_count.html.erb
<table class='table table-bordered'>
  <thead>
    <tr>
      <th>今日の投稿数</th>
      <th>前日の投稿数</th>
      <th>前日比</th>
    </tr>
  </thead>
  <tbody>
      <tr width="90%">
        <td width="30%"><%= @today_book.count %></td>
        <td width="30%"><%= @yesterday_book.count %></td>
        <% if @yesterday_book.count == 0 %>
        <td width="30%">前日の投稿はなし</td>
        <% else %>
        <td width="30%"><% @the_day_before = @today_book.count / @yesterday_book.count.to_f %>
       　<%= (@the_day_before * 100).round %>%</td>
        <% end %>
      </tr>
  </tbody>
</table>

<table class='table table-bordered'>
  <thead>
    <tr>
      <th>今週の投稿数</th>
      <th>前週の投稿数</th>
      <th>前週比</th>
    </tr>
  </thead>
  <tbody>
      <tr width="90%">
        <td width="30%"><%= @this_week_book.count %></td>
        <td width="30%"><%= @last_week_book.count %></td>
        <% if @last_week_book.count == 0 %>
        <td width="30%">前週の投稿はなし</td>
        <% else %>
        <td width="30%"><% @the_week_before = @this_week_book.count / @last_week_book.count.to_f %>
       　<%= (@the_week_before * 100).round %>%</td>
        <% end %>
      </tr>
  </tbody>
</table>

app/views/users/_book_index.html.erb
<table class='table table-bordered'>
  <thead>
    <tr>
      <th>6日前</th>
    　<th>5日前</th>
    　<th>4日前</th>
    　<th>3日前</th>
    　<th>2日前</th>
    　<th>1日前</th>
    　<th>今日</th>
    </tr>
  </thead>
  <tbody>
      <tr width="70%">
        <td width="10%"><%= @six_day_ago_book.count %></td>
        <td width="10%"><%= @five_day_ago_book.count %></td>
        <td width="10%"><%= @four_day_ago_book.count %></td>
        <td width="10%"><%= @three_day_ago_book.count %></td>
        <td width="10%"><%= @two_day_ago_book.count %></td>
        <td width="10%"><%= @yesterday_book.count %></td>
        <td width="10%"><%= @today_book.count %></td>
      </tr>
  </tbody>
</table>

  <canvas id="myLineChart"></canvas>
  <script>
    $(document).on('turbolinks:load', function() {
    var ctx = document.getElementById("myLineChart");
    var myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
            datasets: [
              {
                label: "投稿した本の数",
                data: [
                  <%= @books.created_six_day_ago.count %>,
                  <%= @books.created_five_day_ago.count %>,
                  <%= @books.created_four_day_ago.count %>,
                  <%= @books.created_three_day_ago.count %>,
                  <%= @books.created_two_day_ago.count %>,
                  <%= @yesterday_book.count %>,
                  <%= @today_book.count%>
                ],
                backgroundColor: 'rgba(0,0,0,0)',
                borderColor: 'rgba(255, 80, 120, 1.0)',
                tension: 0.4
              }
            ],
          },

      options: {
          title: {
            display: true,
            text: '7日間の投稿数の比較'
          },
          responsive: true,
          scales: {
            y:{
              suggestedMin: 0,
              suggestedMax: 10
            },
            x:{
              stacked: true
            },
          },
        }
      });
    });
  </script>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
        <% if user != current_user %>
          <% if current_user.following?(user) %>
            <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
        <% end %>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
  </tr>
  <tr>
	  <th>followers</th>
	  <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
  </tr>
</table>

<div class='row'>
  <% if user == current_user && !(user.name == "guestuser") %>
  <!--上記は「もしユーザーがログインしていてゲストユーザーじゃなかったら」という-->
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

<div class='row'>
<% if user != current_user %>
<span>
 <%= render "relationships/follow_btn", user: user %>

 <% if (current_user.following? user) && (user.following? current_user) %>
 <%= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %>
 <% end %>

</span>
<% end %>
</div>

app/views/users/_search.html.erb
<h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr>
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>
  

app/views/users/_search_form.html.erb
<%= form_with url: user_search_path(user), method: :get, local: false do |f| %>
<!--local: falseを追加したらなぜか非同期通信ができた　理由解明する-->
  <%= f.date_field :created_at %>
  <%= f.submit '検索', class: 'btn btn-primary'  %>
<% end %>

<div id="search_result">
<!--上記でjsファイルを-->
  <% if search_book.present? %>
    <%= render 'search', search_book: search_book %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  
  <div class='row'>
    <div class='col-md-3'>
<h2>User info</h2>
<%= render 'info', user: current_user %>

<h2 class="mt-3">New book</h2>
<%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
<h2>Users</h2>
<%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<!--Turbolinksをページごとに無効化-->
<% content_for(:body_attributes) do %>
    data-turbolinks="false"
<% end %>
<!--ここまで-->

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'book_comment', books: @books, user: @user %>
      <%= render 'search_form', user: @user, search_book: @search_book %><br>
      <h3>投稿数の前日比・前週比</h3>
      <%= render 'book_count', books: @books, user: @user %><br>
      <h3>7日間分の投稿数</h3>
      <%= render 'book_index' %>
    </div>
  </div>
</div>