config/routes.rb
Rails.application.routes.draw do
  # get 'relationships/followings'
  # get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search"=>"searches#search"
  get "search_book" => "books#search_book"
  get 'chat/:id', to: 'chats#show', as: 'chat'
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end  
  
  resources :chats, only: [:create]

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update]

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search' => 'users#search'
    # 上記追加
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  has_many :favorited_users, through: :favorites, source: :user

  has_many :book_comments, dependent: :destroy
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  validates :tag,presence:true

  has_many :view_counts, dependent: :destroy

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_two_day_ago, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_three_day_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_four_day_ago, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_five_day_ago, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_six_day_ago, -> { where(created_at: 6.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }






  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end


  def self.search(search_word)
    Book.where(['tag LIKE ?', "#{search_word}"])
  end



end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)
    end
    # 上記３行は投稿の閲覧数を表示させるために
    @user = @book.user
    @new_book = Book.new
    @book_comment = BookComment.new
    # 上記はコメントを投稿するためのインスタンス変数

  end

  def index
    @books = Book.all.order(params[:sort])
    @book = Book.new
    # 下記は課題7aのための記述
    # 課題8dのためにコメントアウトした
    # to  = Time.current.at_beginning_of_day
    # from  = (to - 6.day).at_end_of_day
    # @books = Book.all.sort {|a,b|
      # b.favorited_users.size <=>
      # a.favorited_users.includes(:favorites).where(created_at: from...to).size }
    # @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end


  def search_book
    @book=Book.new
    @books = Book.search(params[:keyword])
  end


  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body, :star, :tag)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_favorite.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td>
          <% if book.favorited_by?(current_user) %>            
            <%= link_to book_favorites_path(book), method: :delete do %>
             ♥<%= book.favorites.count %>
            <% end %>
          <% else %>
            <%= link_to book_favorites_path(book), method: :post do %>
             ♡<%= book.favorites.count %>
            <% end %>
          <% end %>
        </td>
        <td>コメント数:<%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_area :tag, class: 'form-control book_tag' %>
  </div>


  <!--星5段階評価-->
  <% if book.id == nil %>
  <div class="form-group" id="star">
    <%= f.label :star,'Rate', class:'col-md-3 col-form-label' %>
    <%= f.hidden_field :star, id: :book_star %>
  </div>
    <!-- 評価javascript -->
  <script>
  $('#star').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',

    scoreName: 'book[star]',
    half: false,
  });
  </script>
  <% else %>
  <div id="star-rate<%= book.id %>"></div>
  <script>
    $('#star-rate<%= book.id %>').raty({
      size      : 36,
      starOff   : '<%= asset_path('star-off.png') %>',
      starOn    : '<%= asset_path('star-on.png') %>',
      half      : false,
      readOnly: true,
      score: '<%= book.star %>',
    });
  </script>
  <% end %>
  <br>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>

<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_×favorite.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td><%= render "favorites/btn", book: book %></td>
        <td>コメント数:<%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<!--Turbolinksをページごとに無効化-->
<% content_for(:body_attributes) do %>
    data-turbolinks="false"
<% end %>
<!--ここまで-->

<div class='container px-5 px-sm-0'>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to "新しい順", books_path(sort: 'created_at DESC') %> | <%= link_to "古い順", books_path(sort: 'created_at ASC') %>
      | <%= link_to "評価の高い順", books_path(sort: 'star DESC') %>
      
      <%= render 'favorites/favorites', books: @books %>
    </div>
  </div>

</div>

app/views/books/search_book.html.erb
<div class='container px-5 px-sm-0'>  
  <div class='row'>
    <div class='col-md-3'> 
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>      
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>

        <td><%= link_to book.tag, search_book_path(keyword: book.tag) %></td>

        <td><div id="favorite_buttons_<%= book.id %>"><%= render "favorites/favorite-btn", book: book %></div></td>
        <td class="comments_count_<%= book.id %>">コメント数:<%= book.book_comments.count %></td>


        <td id="star-rate<%= book.id %>"></td>
          <script>
            $('#star-rate<%= book.id %>').raty({
              size      : 36,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              half      : false,
              readOnly: true,
              score: '<%= book.star %>',
            });
          </script>

        <td class="view_count">閲覧数:<%= book.view_counts.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
  </div>
    </div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', book: @book, user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          
          <td><%= @book.tag %></td>
          
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
          <td id="favorite_buttons_<%= @book.id %>"><%= render "favorites/favorite-btn", book: @book %></td>
          <td class="comments_count_<%= @book.id %>">コメント数:<%= @book.book_comments.count %></td>
          
          <td id="star-rate<%= @book.id %>"></td>
          <script>
            $('#star-rate<%= @book.id %>').raty({
              size      : 36,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              half      : false,
              readOnly: true,
              score: '<%= @book.star %>',
            });
          </script>          
          
          <td class="view_count">閲覧数:<%= @book.view_counts.count %></td>
        </tr>
      </table>

      <div class="book_comments">
        <%= render "book_comments/index", book: @book %>
      </div>

        <%= render "book_comments/form", book: @book, book_comment: @book_comment %>

    </div>
  </div>
</div>